batch_size: '1'
check_integrity: false
data_sampling: null
decontamination_ngrams_path: null
description_dict_path: null
device: null
end_range: null
fewshot_sampling: random
model: hf-causal-experimental
model_args: pretrained=mtc/mistralai-Mistral-7B-v0.1-arxiv-summarization-5000-finetuned-no_quantization-best,trust_remote_code=False,use_accelerate=True,dtype=bfloat16,load_in_8bit=False,attn_implementation=flash_attention_2
no_cache: true
num_fewshot: 0
output_base_path: results
output_path: null
seed: 42
start_range: null
task_configs:
-   prompt_template: configs/prompt_templates/domain_adaptation_finetuned.json
    prompt_version: prompt_v3_summarization_finetuned
    task_name: arxiv_2k_domain_adaptation_summarization
wandb_on: true
wandb_project_name: domain_adaptation
write_out: true
