batch_size: '2'
check_integrity: false
data_sampling: null
decontamination_ngrams_path: null
description_dict_path: null
device: null
fewshot_sampling: stratified
limit: null
model: hf-causal-experimental
model_args: pretrained=mtc/LeoLM-leo-mistral-hessianai-7b-classification-with-explanation-3-epochs-finetuned,trust_remote_code=False,use_accelerate=True,dtype=bfloat16,load_in_8bit=False,use_flash_attention_2=True
no_cache: true
num_fewshot: 0
output_base_path: results
output_path: null
seed: 42
task_configs:
-   prompt_template: configs/prompt_templates/faithfulness_benchmark_final_swisstext23_with_explanation_multi_label.json
    prompt_version: all_labels_german_with_explanation_finetuned
    task_name: seahorse_attribution_with_explanation_multi_label
wandb_on: true
write_out: true
