model: hf-seq2seq
model_args: "pretrained=google/flan-t5-small,batch_size=1"
tasks: "germanquad_open_qa"
num_fewshot: 0
batch_size: null
device: cuda:0
output_path: null
limit: 5
data_sampling: null
no_cache: true
decontamination_ngrams_path: null
description_dict_path: null
check_integrity: true
write_out: true
output_base_path: "germanquad_results/flan_t5"
wandb_on: true
