batch_size: '2'
check_integrity: false
data_sampling: null
decontamination_ngrams_path: null
description_dict_path: null
device: null
end_range: null
fewshot_sampling: stratified
model: hf-causal-experimental
model_args: pretrained=mistralai/Mistral-7B-v0.1,trust_remote_code=False,use_accelerate=True,dtype=bfloat16,load_in_8bit=False,attn_implementation=flash_attention_2,max_length=4096
no_cache: true
num_fewshot: 6
output_base_path: results
output_path: null
seed: 42
start_range: null
task_configs:
-   prompt_template: configs/prompt_templates/faithfulness_benchmark_final_swisstext23_multi_label.json
    prompt_version: all_labels_english
    task_name: xsum_faith_multi_label
wandb_on: true
write_out: true
