batch_size: '1'
check_integrity: false
data_sampling: null
decontamination_ngrams_path: null
description_dict_path: null
device: null
end_range: 3
fewshot_sampling: stratified
model: ctransformers-casual
model_args: pretrained=mtc/leo-mistral-absinth-finetuned-3-epochs-GGUF,subfolder=leo-mistral-7b-absinth-finetuned-3-epochs-q4_k_m.gguf,max_length=4096,gpu_layers=0
no_cache: true
num_fewshot: 0
output_base_path: results
output_path: null
seed: 42
start_range: null
task_configs:
-   prompt_template: configs/prompt_templates/faithfulness_benchmark_final_swisstext23_with_explanation_multi_label.json
    prompt_version: all_labels_german_with_explanation_finetuned
    task_name: faithfulness_benchmark_final_swisstext23_with_explanation_multi_label
wandb_on: true
write_out: true
