batch_size: '1'
seed: 42
check_integrity: false
data_sampling: null
decontamination_ngrams_path: null
description_dict_path: null
device: null
start_range: null
end_range: null
model: hf-causal-experimental
model_args: pretrained=NousResearch/Llama-2-7b-hf,trust_remote_code=True,use_accelerate=True
no_cache: true
num_fewshot: 0
fewshot_sampling: "packed"
output_base_path: results
output_path: null
wandb_on: true
write_out: true
